// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sanmo-Labs/rumpty-cli/internal/api (interfaces: ClientAPI)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_client.go -package=mocks . ClientAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/Sanmo-Labs/rumpty-cli/internal/api"
	gomock "go.uber.org/mock/gomock"
)

// MockClientAPI is a mock of ClientAPI interface.
type MockClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockClientAPIMockRecorder
	isgomock struct{}
}

// MockClientAPIMockRecorder is the mock recorder for MockClientAPI.
type MockClientAPIMockRecorder struct {
	mock *MockClientAPI
}

// NewMockClientAPI creates a new mock instance.
func NewMockClientAPI(ctrl *gomock.Controller) *MockClientAPI {
	mock := &MockClientAPI{ctrl: ctrl}
	mock.recorder = &MockClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAPI) EXPECT() *MockClientAPIMockRecorder {
	return m.recorder
}

// DeleteVM mocks base method.
func (m *MockClientAPI) DeleteVM(ctx context.Context, workspace, vmUID, idempotency string) (api.VMOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVM", ctx, workspace, vmUID, idempotency)
	ret0, _ := ret[0].(api.VMOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteVM indicates an expected call of DeleteVM.
func (mr *MockClientAPIMockRecorder) DeleteVM(ctx, workspace, vmUID, idempotency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVM", reflect.TypeOf((*MockClientAPI)(nil).DeleteVM), ctx, workspace, vmUID, idempotency)
}

// ExposeVMApp mocks base method.
func (m *MockClientAPI) ExposeVMApp(ctx context.Context, workspace, vmUID string, req api.ExposeVMAppRequest, idempotency string) (api.ExposeVMAppResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExposeVMApp", ctx, workspace, vmUID, req, idempotency)
	ret0, _ := ret[0].(api.ExposeVMAppResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExposeVMApp indicates an expected call of ExposeVMApp.
func (mr *MockClientAPIMockRecorder) ExposeVMApp(ctx, workspace, vmUID, req, idempotency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExposeVMApp", reflect.TypeOf((*MockClientAPI)(nil).ExposeVMApp), ctx, workspace, vmUID, req, idempotency)
}

// UnexposeVMApp mocks base method.
func (m *MockClientAPI) UnexposeVMApp(ctx context.Context, workspace, vmUID, app string, idempotency string) (api.UnexposeVMAppResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnexposeVMApp", ctx, workspace, vmUID, app, idempotency)
	ret0, _ := ret[0].(api.UnexposeVMAppResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnexposeVMApp indicates an expected call of UnexposeVMApp.
func (mr *MockClientAPIMockRecorder) UnexposeVMApp(ctx, workspace, vmUID, app, idempotency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnexposeVMApp", reflect.TypeOf((*MockClientAPI)(nil).UnexposeVMApp), ctx, workspace, vmUID, app, idempotency)
}

// GetOperation mocks base method.
func (m *MockClientAPI) GetOperation(ctx context.Context, workspace, operationID string) (api.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperation", ctx, workspace, operationID)
	ret0, _ := ret[0].(api.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperation indicates an expected call of GetOperation.
func (mr *MockClientAPIMockRecorder) GetOperation(ctx, workspace, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperation", reflect.TypeOf((*MockClientAPI)(nil).GetOperation), ctx, workspace, operationID)
}

// IssueSSHCert mocks base method.
func (m *MockClientAPI) IssueSSHCert(ctx context.Context, workspace string, req api.CertRequest) (api.CertResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueSSHCert", ctx, workspace, req)
	ret0, _ := ret[0].(api.CertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueSSHCert indicates an expected call of IssueSSHCert.
func (mr *MockClientAPIMockRecorder) IssueSSHCert(ctx, workspace, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueSSHCert", reflect.TypeOf((*MockClientAPI)(nil).IssueSSHCert), ctx, workspace, req)
}

// ListVMs mocks base method.
func (m *MockClientAPI) ListVMs(ctx context.Context, workspace string) ([]api.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMs", ctx, workspace)
	ret0, _ := ret[0].([]api.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMs indicates an expected call of ListVMs.
func (mr *MockClientAPIMockRecorder) ListVMs(ctx, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMs", reflect.TypeOf((*MockClientAPI)(nil).ListVMs), ctx, workspace)
}

// ListVMApps mocks base method.
func (m *MockClientAPI) ListVMApps(ctx context.Context, workspace, vmUID string) ([]api.VMApp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMApps", ctx, workspace, vmUID)
	ret0, _ := ret[0].([]api.VMApp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMApps indicates an expected call of ListVMApps.
func (mr *MockClientAPIMockRecorder) ListVMApps(ctx, workspace, vmUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMApps", reflect.TypeOf((*MockClientAPI)(nil).ListVMApps), ctx, workspace, vmUID)
}

// ListWorkspaces mocks base method.
func (m *MockClientAPI) ListWorkspaces(ctx context.Context) ([]api.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkspaces", ctx)
	ret0, _ := ret[0].([]api.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspaces indicates an expected call of ListWorkspaces.
func (mr *MockClientAPIMockRecorder) ListWorkspaces(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspaces", reflect.TypeOf((*MockClientAPI)(nil).ListWorkspaces), ctx)
}

// Logout mocks base method.
func (m *MockClientAPI) Logout(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockClientAPIMockRecorder) Logout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockClientAPI)(nil).Logout), ctx)
}

// Me mocks base method.
func (m *MockClientAPI) Me(ctx context.Context) (api.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx)
	ret0, _ := ret[0].(api.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockClientAPIMockRecorder) Me(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockClientAPI)(nil).Me), ctx)
}

// PollDeviceToken mocks base method.
func (m *MockClientAPI) PollDeviceToken(ctx context.Context, deviceCode string) (api.DeviceAuthPollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollDeviceToken", ctx, deviceCode)
	ret0, _ := ret[0].(api.DeviceAuthPollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollDeviceToken indicates an expected call of PollDeviceToken.
func (mr *MockClientAPIMockRecorder) PollDeviceToken(ctx, deviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollDeviceToken", reflect.TypeOf((*MockClientAPI)(nil).PollDeviceToken), ctx, deviceCode)
}

// RebootVM mocks base method.
func (m *MockClientAPI) RebootVM(ctx context.Context, workspace, vmUID, idempotency string) (api.VMOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootVM", ctx, workspace, vmUID, idempotency)
	ret0, _ := ret[0].(api.VMOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebootVM indicates an expected call of RebootVM.
func (mr *MockClientAPIMockRecorder) RebootVM(ctx, workspace, vmUID, idempotency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootVM", reflect.TypeOf((*MockClientAPI)(nil).RebootVM), ctx, workspace, vmUID, idempotency)
}

// StartDevice mocks base method.
func (m *MockClientAPI) StartDevice(ctx context.Context) (api.DeviceAuthStartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDevice", ctx)
	ret0, _ := ret[0].(api.DeviceAuthStartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDevice indicates an expected call of StartDevice.
func (mr *MockClientAPIMockRecorder) StartDevice(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDevice", reflect.TypeOf((*MockClientAPI)(nil).StartDevice), ctx)
}

// StartVM mocks base method.
func (m *MockClientAPI) StartVM(ctx context.Context, workspace, vmUID, idempotency string) (api.VMOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartVM", ctx, workspace, vmUID, idempotency)
	ret0, _ := ret[0].(api.VMOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartVM indicates an expected call of StartVM.
func (mr *MockClientAPIMockRecorder) StartVM(ctx, workspace, vmUID, idempotency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartVM", reflect.TypeOf((*MockClientAPI)(nil).StartVM), ctx, workspace, vmUID, idempotency)
}

// StopVM mocks base method.
func (m *MockClientAPI) StopVM(ctx context.Context, workspace, vmUID, idempotency string) (api.VMOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopVM", ctx, workspace, vmUID, idempotency)
	ret0, _ := ret[0].(api.VMOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopVM indicates an expected call of StopVM.
func (mr *MockClientAPIMockRecorder) StopVM(ctx, workspace, vmUID, idempotency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopVM", reflect.TypeOf((*MockClientAPI)(nil).StopVM), ctx, workspace, vmUID, idempotency)
}
